### ISSUE TITLE
兼容vim

### ISSUE THREAD

**Issue by oeyoews** [MoYuM/moyu-leap#1]
手动修改了搜索快捷键， 似乎还是不兼容vim

**Comment by MoYuM** [comment]
目前还找不到兼容 vim 插件的办法，因为 moyu-leap 和 vim 一样，基本原理都是覆盖 vscode 默认的 type 事件。vim 已经覆盖了 type 事件之后，moyu-leap 就无法覆盖了。

你可以试试 vim 插件里面的 esaymotion 功能，能达到类似的效果

**Comment by oeyoews** [comment]
嗯， 用过easymotion， 他的那套逻辑确实没有flash.nvim 用着顺手
